name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      GITEA_URL: http://localhost:3000
      GITEA_USER: ${{ secrets.GITEA_USER }}
      GITEA_PASSWORD: ${{ secrets.GITEA_PASSWORD }}
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - name: Run smoke tests  
        run: poetry run pytest -m smoke -sv

  regression:
    needs: smoke
    runs-on: ubuntu-latest
    env:
      GITEA_URL: http://localhost:3000
      GITEA_USER: ${{ secrets.GITEA_USER }}
      GITEA_PASSWORD: ${{ secrets.GITEA_PASSWORD }}
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - name: Run regression tests  
        run: poetry run pytest -m regression -sv 